version: '3'

services:
  app:
    image: ${REGISTRY}/sampleformetrics/app
    links:
      - app-postgres-db:app-postgres-db
    ports:
    #   - 80:80
    network_mode: podman

  app-postgres-db:
    image: ${REGISTRY}/sampleformetrics/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
    network_mode: podman
volumes:
  DB:
