# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-16T14:57:42Z"
  labels:
    app: pod-sampleformetrics
  name: pod-sampleformetrics
spec:
  ports:
  - name: "80"
    nodePort: 30537
    port: 80
    targetPort: 80
  selector:
    app: pod-sampleformetrics
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/sampleformetrics-app-1: container
    io.kubernetes.cri-o.ContainerType/sampleformetrics-app-postgres-db-1: container
    io.kubernetes.cri-o.SandboxID/sampleformetrics-app-1: b8def0b5bd85e69ce96502dfcbd4b94e40a61fe50fe0a1b3761352ade9eff3f
    io.kubernetes.cri-o.SandboxID/sampleformetrics-app-postgres-db-1: b8def0b5bd85e69ce96502dfcbd4b94e40a61fe50fe0a1b3761352ade9eff3f
    io.kubernetes.cri-o.TTY/sampleformetrics-app-1: "false"
    io.kubernetes.cri-o.TTY/sampleformetrics-app-postgres-db-1: "false"
    io.podman.annotations.autoremove/sampleformetrics-app-1: "FALSE"
    io.podman.annotations.autoremove/sampleformetrics-app-postgres-db-1: "FALSE"
    io.podman.annotations.init/sampleformetrics-app-1: "FALSE"
    io.podman.annotations.init/sampleformetrics-app-postgres-db-1: "FALSE"
    io.podman.annotations.privileged/sampleformetrics-app-1: "FALSE"
    io.podman.annotations.privileged/sampleformetrics-app-postgres-db-1: "FALSE"
    io.podman.annotations.publish-all/sampleformetrics-app-1: "FALSE"
    io.podman.annotations.publish-all/sampleformetrics-app-postgres-db-1: "FALSE"
    org.opencontainers.image.base.digest/sampleformetrics-app-1: sha256:4e5e4873d8229fec68b6f9673116f39519b76134b0d9e9f3cb8a9ea0
    org.opencontainers.image.base.digest/sampleformetrics-app-postgres-db-1: sha256:7f1045412a9771cbea82dec07ca661435050c9d2569622bb5c917a8e
    org.opencontainers.image.base.name/sampleformetrics-app-1: docker.io/flexberry/mono-xsp:latest
    org.opencontainers.image.base.name/sampleformetrics-app-postgres-db-1: docker.io/flexberry/alt.p8-postgresql:latest
  creationTimestamp: "2023-02-16T14:57:42Z"
  labels:
    app: pod-sampleformetrics
  name: pod-sampleformetrics
spec:
  automountServiceAccountToken: false
  containers:
  - image: dh.ics.perm.ru/sampleformetrics/postgre-sql:latest
    name: sampleformetrics-app-postgres-db-1
    ports:
    - containerPort: 80
      hostPort: 80
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/pgsql/data/
      name: sampleformetrics-db-pvc
  - image: dh.ics.perm.ru/sampleformetrics/app:latest
    name: sampleformetrics-app-1
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  enableServiceLinks: false
  hostAliases:
  - hostnames:
    - app-postgres-db
    ip: 127.0.0.1
  hostname: sampleformetrics
  restartPolicy: Never
  volumes:
  - name: sampleformetrics-db-pvc
    persistentVolumeClaim:
      claimName: sampleformetrics-db
status: {}

