//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SampleForMetrics
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Blog post.
    /// </summary>
    // *** Start programmer edit section *** (BlogPost CustomAttributes)

    // *** End programmer edit section *** (BlogPost CustomAttributes)
    [AutoAltered()]
    [Caption("Blog post")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BlogPostE", new string[] {
            "Text as \'Text\'",
            "Date as \'Date\'",
            "PostStatus as \'Post status\'",
            "PostAuthor as \'Post author\'",
            "PostAuthor.Name as \'Name\'"}, Hidden=new string[] {
            "PostAuthor.Name"})]
    [AssociatedDetailViewAttribute("BlogPostE", "PostTag", "PostTagE", true, "", "Post tag", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("BlogPostE", "PostAuthor", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("BlogPostL", new string[] {
            "Text as \'Text\'",
            "Date as \'Date\'",
            "PostStatus as \'Post status\'",
            "PostAuthor.Name as \'Name\'"})]
    public class BlogPost : ICSSoft.STORMNET.DataObject
    {
        
        private string fText;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fDate;
        
        private IIS.SampleForMetrics.PostStatus fPostStatus;
        
        private IIS.SampleForMetrics.PostAuthor fPostAuthor;
        
        private IIS.SampleForMetrics.DetailArrayOfPostTag fPostTag;
        
        // *** Start programmer edit section *** (BlogPost CustomMembers)

        // *** End programmer edit section *** (BlogPost CustomMembers)

        
        /// <summary>
        /// Text.
        /// </summary>
        // *** Start programmer edit section *** (BlogPost.Text CustomAttributes)

        // *** End programmer edit section *** (BlogPost.Text CustomAttributes)
        [StrLen(255)]
        public virtual string Text
        {
            get
            {
                // *** Start programmer edit section *** (BlogPost.Text Get start)

                // *** End programmer edit section *** (BlogPost.Text Get start)
                string result = this.fText;
                // *** Start programmer edit section *** (BlogPost.Text Get end)

                // *** End programmer edit section *** (BlogPost.Text Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BlogPost.Text Set start)

                // *** End programmer edit section *** (BlogPost.Text Set start)
                this.fText = value;
                // *** Start programmer edit section *** (BlogPost.Text Set end)

                // *** End programmer edit section *** (BlogPost.Text Set end)
            }
        }
        
        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (BlogPost.Date CustomAttributes)

        // *** End programmer edit section *** (BlogPost.Date CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (BlogPost.Date Get start)

                // *** End programmer edit section *** (BlogPost.Date Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fDate;
                // *** Start programmer edit section *** (BlogPost.Date Get end)

                // *** End programmer edit section *** (BlogPost.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BlogPost.Date Set start)

                // *** End programmer edit section *** (BlogPost.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (BlogPost.Date Set end)

                // *** End programmer edit section *** (BlogPost.Date Set end)
            }
        }
        
        /// <summary>
        /// PostStatus.
        /// </summary>
        // *** Start programmer edit section *** (BlogPost.PostStatus CustomAttributes)

        // *** End programmer edit section *** (BlogPost.PostStatus CustomAttributes)
        public virtual IIS.SampleForMetrics.PostStatus PostStatus
        {
            get
            {
                // *** Start programmer edit section *** (BlogPost.PostStatus Get start)

                // *** End programmer edit section *** (BlogPost.PostStatus Get start)
                IIS.SampleForMetrics.PostStatus result = this.fPostStatus;
                // *** Start programmer edit section *** (BlogPost.PostStatus Get end)

                // *** End programmer edit section *** (BlogPost.PostStatus Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BlogPost.PostStatus Set start)

                // *** End programmer edit section *** (BlogPost.PostStatus Set start)
                this.fPostStatus = value;
                // *** Start programmer edit section *** (BlogPost.PostStatus Set end)

                // *** End programmer edit section *** (BlogPost.PostStatus Set end)
            }
        }
        
        /// <summary>
        /// Blog post.
        /// </summary>
        // *** Start programmer edit section *** (BlogPost.PostAuthor CustomAttributes)

        // *** End programmer edit section *** (BlogPost.PostAuthor CustomAttributes)
        public virtual IIS.SampleForMetrics.PostAuthor PostAuthor
        {
            get
            {
                // *** Start programmer edit section *** (BlogPost.PostAuthor Get start)

                // *** End programmer edit section *** (BlogPost.PostAuthor Get start)
                IIS.SampleForMetrics.PostAuthor result = this.fPostAuthor;
                // *** Start programmer edit section *** (BlogPost.PostAuthor Get end)

                // *** End programmer edit section *** (BlogPost.PostAuthor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BlogPost.PostAuthor Set start)

                // *** End programmer edit section *** (BlogPost.PostAuthor Set start)
                this.fPostAuthor = value;
                // *** Start programmer edit section *** (BlogPost.PostAuthor Set end)

                // *** End programmer edit section *** (BlogPost.PostAuthor Set end)
            }
        }
        
        /// <summary>
        /// Blog post.
        /// </summary>
        // *** Start programmer edit section *** (BlogPost.PostTag CustomAttributes)

        // *** End programmer edit section *** (BlogPost.PostTag CustomAttributes)
        public virtual IIS.SampleForMetrics.DetailArrayOfPostTag PostTag
        {
            get
            {
                // *** Start programmer edit section *** (BlogPost.PostTag Get start)

                // *** End programmer edit section *** (BlogPost.PostTag Get start)
                if ((this.fPostTag == null))
                {
                    this.fPostTag = new IIS.SampleForMetrics.DetailArrayOfPostTag(this);
                }
                IIS.SampleForMetrics.DetailArrayOfPostTag result = this.fPostTag;
                // *** Start programmer edit section *** (BlogPost.PostTag Get end)

                // *** End programmer edit section *** (BlogPost.PostTag Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BlogPost.PostTag Set start)

                // *** End programmer edit section *** (BlogPost.PostTag Set start)
                this.fPostTag = value;
                // *** Start programmer edit section *** (BlogPost.PostTag Set end)

                // *** End programmer edit section *** (BlogPost.PostTag Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BlogPostE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BlogPostE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BlogPostE", typeof(IIS.SampleForMetrics.BlogPost));
                }
            }
            
            /// <summary>
            /// "BlogPostL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BlogPostL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BlogPostL", typeof(IIS.SampleForMetrics.BlogPost));
                }
            }
        }
    }
}
