//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SampleForMetrics
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Post tag.
    /// </summary>
    // *** Start programmer edit section *** (PostTag CustomAttributes)

    // *** End programmer edit section *** (PostTag CustomAttributes)
    [AutoAltered()]
    [Caption("Post tag")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PostTagE", new string[] {
            "Order as \'Order\'",
            "TagType as \'Tag type\'",
            "TagType.Name as \'Name\'"}, Hidden=new string[] {
            "TagType.Name"})]
    [MasterViewDefineAttribute("PostTagE", "TagType", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class PostTag : ICSSoft.STORMNET.DataObject
    {
        
        private int fOrder;
        
        private IIS.SampleForMetrics.TagType fTagType;
        
        private IIS.SampleForMetrics.BlogPost fBlogPost;
        
        // *** Start programmer edit section *** (PostTag CustomMembers)

        // *** End programmer edit section *** (PostTag CustomMembers)

        
        /// <summary>
        /// Order.
        /// </summary>
        // *** Start programmer edit section *** (PostTag.Order CustomAttributes)

        // *** End programmer edit section *** (PostTag.Order CustomAttributes)
        public virtual int Order
        {
            get
            {
                // *** Start programmer edit section *** (PostTag.Order Get start)

                // *** End programmer edit section *** (PostTag.Order Get start)
                int result = this.fOrder;
                // *** Start programmer edit section *** (PostTag.Order Get end)

                // *** End programmer edit section *** (PostTag.Order Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PostTag.Order Set start)

                // *** End programmer edit section *** (PostTag.Order Set start)
                this.fOrder = value;
                // *** Start programmer edit section *** (PostTag.Order Set end)

                // *** End programmer edit section *** (PostTag.Order Set end)
            }
        }
        
        /// <summary>
        /// Post tag.
        /// </summary>
        // *** Start programmer edit section *** (PostTag.TagType CustomAttributes)

        // *** End programmer edit section *** (PostTag.TagType CustomAttributes)
        [NotNull()]
        public virtual IIS.SampleForMetrics.TagType TagType
        {
            get
            {
                // *** Start programmer edit section *** (PostTag.TagType Get start)

                // *** End programmer edit section *** (PostTag.TagType Get start)
                IIS.SampleForMetrics.TagType result = this.fTagType;
                // *** Start programmer edit section *** (PostTag.TagType Get end)

                // *** End programmer edit section *** (PostTag.TagType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PostTag.TagType Set start)

                // *** End programmer edit section *** (PostTag.TagType Set start)
                this.fTagType = value;
                // *** Start programmer edit section *** (PostTag.TagType Set end)

                // *** End programmer edit section *** (PostTag.TagType Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.SampleForMetrics.BlogPost.
        /// </summary>
        // *** Start programmer edit section *** (PostTag.BlogPost CustomAttributes)

        // *** End programmer edit section *** (PostTag.BlogPost CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.SampleForMetrics.BlogPost BlogPost
        {
            get
            {
                // *** Start programmer edit section *** (PostTag.BlogPost Get start)

                // *** End programmer edit section *** (PostTag.BlogPost Get start)
                IIS.SampleForMetrics.BlogPost result = this.fBlogPost;
                // *** Start programmer edit section *** (PostTag.BlogPost Get end)

                // *** End programmer edit section *** (PostTag.BlogPost Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PostTag.BlogPost Set start)

                // *** End programmer edit section *** (PostTag.BlogPost Set start)
                this.fBlogPost = value;
                // *** Start programmer edit section *** (PostTag.BlogPost Set end)

                // *** End programmer edit section *** (PostTag.BlogPost Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PostTagE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PostTagE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PostTagE", typeof(IIS.SampleForMetrics.PostTag));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of PostTag.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfPostTag CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfPostTag CustomAttributes)
    public class DetailArrayOfPostTag : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.SampleForMetrics.DetailArrayOfPostTag members)

        // *** End programmer edit section *** (IIS.SampleForMetrics.DetailArrayOfPostTag members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type PostTag by index.
        /// </summary>
        /// <summary>
        /// Adds object with type PostTag.
        /// </summary>
        public DetailArrayOfPostTag(IIS.SampleForMetrics.BlogPost fBlogPost) : 
                base(typeof(PostTag), ((ICSSoft.STORMNET.DataObject)(fBlogPost)))
        {
        }
        
        public IIS.SampleForMetrics.PostTag this[int index]
        {
            get
            {
                return ((IIS.SampleForMetrics.PostTag)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.SampleForMetrics.PostTag dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
