//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SampleForMetrics
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Post status.
    /// </summary>
    // *** Start programmer edit section *** (PostStatus CustomAttributes)

    // *** End programmer edit section *** (PostStatus CustomAttributes)
    public enum PostStatus
    {
        
        // *** Start programmer edit section *** (PostStatus.Draft CustomAttributes)

        // *** End programmer edit section *** (PostStatus.Draft CustomAttributes)
        Draft,
        
        // *** Start programmer edit section *** (PostStatus.Published CustomAttributes)

        // *** End programmer edit section *** (PostStatus.Published CustomAttributes)
        Published,
        
        // *** Start programmer edit section *** (PostStatus.Deleted CustomAttributes)

        // *** End programmer edit section *** (PostStatus.Deleted CustomAttributes)
        Deleted,
    }
}
