//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SampleForMetrics
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Post author.
    /// </summary>
    // *** Start programmer edit section *** (PostAuthor CustomAttributes)

    // *** End programmer edit section *** (PostAuthor CustomAttributes)
    [AutoAltered()]
    [Caption("Post author")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PostAuthorE", new string[] {
            "Name as \'Name\'"})]
    [View("PostAuthorL", new string[] {
            "Name as \'Name\'"})]
    public class PostAuthor : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (PostAuthor CustomMembers)

        // *** End programmer edit section *** (PostAuthor CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (PostAuthor.Name CustomAttributes)

        // *** End programmer edit section *** (PostAuthor.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (PostAuthor.Name Get start)

                // *** End programmer edit section *** (PostAuthor.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (PostAuthor.Name Get end)

                // *** End programmer edit section *** (PostAuthor.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PostAuthor.Name Set start)

                // *** End programmer edit section *** (PostAuthor.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (PostAuthor.Name Set end)

                // *** End programmer edit section *** (PostAuthor.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PostAuthorE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PostAuthorE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PostAuthorE", typeof(IIS.SampleForMetrics.PostAuthor));
                }
            }
            
            /// <summary>
            /// "PostAuthorL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PostAuthorL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PostAuthorL", typeof(IIS.SampleForMetrics.PostAuthor));
                }
            }
        }
    }
}
