//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SampleForMetrics
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Tag type.
    /// </summary>
    // *** Start programmer edit section *** (TagType CustomAttributes)

    // *** End programmer edit section *** (TagType CustomAttributes)
    [AutoAltered()]
    [Caption("Tag type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TagTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("TagTypeL", new string[] {
            "Name as \'Name\'"})]
    public class TagType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (TagType CustomMembers)

        // *** End programmer edit section *** (TagType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (TagType.Name CustomAttributes)

        // *** End programmer edit section *** (TagType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (TagType.Name Get start)

                // *** End programmer edit section *** (TagType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (TagType.Name Get end)

                // *** End programmer edit section *** (TagType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TagType.Name Set start)

                // *** End programmer edit section *** (TagType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (TagType.Name Set end)

                // *** End programmer edit section *** (TagType.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TagTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TagTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TagTypeE", typeof(IIS.SampleForMetrics.TagType));
                }
            }
            
            /// <summary>
            /// "TagTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TagTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TagTypeL", typeof(IIS.SampleForMetrics.TagType));
                }
            }
        }
    }
}
